version: '3.8'

services:
  db_user:
    image: 'mysql:5.7'
    volumes:
      - dbuser_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always
    networks:
      - laravel

  phpmyadminuser:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db_user
    links:
      - db_user
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db_user
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - laravel

  service-user:
    image: 'shinsenter/laravel:latest'
    container_name: service-user
    depends_on:
      - db_user
    links:
      - db_user
    ports:
      - "7001:80"
    volumes:
      - './service-user/:/var/www/html'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db_user
      - DB_PORT=3306
      - DB_DATABASE=userdb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    restart: always
    networks:
      - laravel

  service-resep:
    build:
      context: ./service-resep
    container_name: service-resep
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root@db_resep:3306/db_resep
      - PORT=3000
    depends_on:
      - db_resep
    restart: always

  service-permintaan-resep:
    build:
      context: ./service-permintaan-resep
    container_name: service-permintaan-resep
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root@db_resep:3306/db_resep
      - PORT=3001
    depends_on:
      - db_resep
    restart: always

  service-komentar:
    build:
      context: ./service-komentar
    container_name: service-komentar
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=mysql://root@db_resep:3306/db_resep
      - PORT=3002
    depends_on:
      - db_resep
    restart: always

  db_resep:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db_resep
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db_resep
      PMA_USER: root
      PMA_PASSWORD: ""
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    depends_on:
      - db_resep
    restart: always

volumes:
  mysql-data:
  dbuser_data:

networks:
  laravel:
    driver: bridge
